#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import Gradient kivy_gradient.Gradient
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import Factory kivy.factory.Factory
#:import NoTransition kivy.uix.screenmanager.NoTransition
#:import PixelTransition kivy.garden.moretransitions.PixelTransition
#:import BlurTransition kivy.garden.moretransitions.BlurTransition
#:import RVBTransition kivy.garden.moretransitions.RVBTransition
#:import RippleTransition kivy.garden.moretransitions.RippleTransition



<Setting@Popup>

    auto_dismiss: True
    size_hint: 0.6, 0.6
    pos_hint: {"x": 0.2, "top": 0.8}

    canvas:
        Color:
            rgb: (255/255, 170/255, 235/255)
        Line:
            width: 47
            rectangle: self.x, self.y, self.width, self.height

    FloatLayout:
        canvas:
            Color:
                rgb: (255/255, 170/255, 235/255)
            Rectangle:
                pos: self.pos
                size: self.size
            Line:
                width: 2
                rectangle: self.x, self.y, self.width, self.height

        Button:
            size_hint: (.8, .3)
            pos_hint: {"x":.1, "y":.625}
            background_normal: ''
            background_color: 1, .5, .6, .85
            font_size: 60
            bold: True
            color: 200/255, 0/255, 70/255, 1
            text: "Fullscreen"
            on_release: root.dismiss()
            on_release: app.fullscreen()

        Button:
            size_hint: (.8, .3)
            pos_hint: {"x":.1, "y":.2}
            background_normal: ''
            background_color: 1, .5, .6, .85
            font_size: 42
            bold: True
            color: 200/255, 0/255, 70/255, 1
            text: "Turn off fullscreen"
            on_release: root.dismiss()
            on_release: app.notfullscreen()
<Question@Popup>

    auto_dismiss: True
    size_hint: 0.6, 0.6
    pos_hint: {"x": 0.2, "top": 0.8}

    canvas:
        Color:
            rgb: (255/255, 170/255, 235/255)
        Line:
            width: 47
            rectangle: self.x, self.y, self.width, self.height

    FloatLayout:
        canvas:
            Color:
                rgb: (255/255, 170/255, 235/255)
            Rectangle:
                pos: self.pos
                size: self.size
            Line:
                width: 2
                rectangle: self.x, self.y, self.width, self.height

        Label:
            pos_hint: {"x": -0.0, "top": 1.45}
            background_color: 1, 0, 0, 1
            text: "MADE BY ALEX ZHOU (CLINCOT)!"
            font_size: 25
            bold: True
            color: 200/255, 0/255, 70/255, 1

        Label:
            pos_hint: {"x": -0.0, "top": 1.35}
            background_color: 1, 0, 0, 1
            text: "There are multiple endings to"
            font_size: 25
            bold: True
            color: 200/255, 0/255, 70/255, 1

        Label:
            pos_hint: {"x": -0.0, "top": 1.25}
            background_color: 1, 0, 0, 1
            text: "each path. If your game closes,"
            font_size: 25
            bold: True
            color: 200/255, 0/255, 70/255, 1

        Label:
            pos_hint: {"x": -0.0, "top": 1.15}
            background_color: 1, 0, 0, 1
            text: "that means you either died or"
            font_size: 25
            bold: True
            color: 200/255, 0/255, 70/255, 1

        Label:
            pos_hint: {"x": -0.0, "top": 1.05}
            background_color: 1, 0, 0, 1
            text: "you reached an ending. Each"
            font_size: 25
            bold: True
            color: 200/255, 0/255, 70/255, 1

        Label:
            pos_hint: {"x": -0.0, "top": .95}
            background_color: 1, 0, 0, 1
            text: "action you do affects your "
            font_size: 25
            bold: True
            color: 200/255, 0/255, 70/255, 1

        Label:
            pos_hint: {"x": -0.0, "top": .85}
            background_color: 1, 0, 0, 1
            text: "affinity, which decides what"
            font_size: 25
            bold: True
            color: 200/255, 0/255, 70/255, 1

        Label:
            pos_hint: {"x": -0.0, "top": .75}
            background_color: 1, 0, 0, 1
            text: "the dialogue, path, and ending"
            font_size: 25
            bold: True
            color: 200/255, 0/255, 70/255, 1

        Label:
            pos_hint: {"x": -0.0, "top": .68}
            background_color: 1, 0, 0, 1
            text: "you get."
            font_size: 25
            bold: True
            color: 200/255, 0/255, 70/255, 1

<FirstScreen>:
    canvas:
        #Color:
        #    rgb: (255/255, 170/255, 235/255)
        Rectangle:
            pos: self.pos
            size: self.size
            texture:
                Gradient.vertical(
                get_color_from_hex("E91E63"),
                get_color_from_hex("FCE4EC"),
                get_color_from_hex("2962FF")
                )

    Button:
        size_hint: (.2025, .0765)
        pos_hint: {"x":.8885, "y":.9235}
        background_normal: ''
        background_color: 200/255, 0, 70/255

    Image:
        size_hint: (1, 1)
        pos_hint: {"x": 0, "y": 0}
        source: 'images/floating_heart_zip.zip'
        allow_stretch: True
        keep_ratio: False
        anim_delay: 0.05

    Image:
        size_hint: (1, 2)
        pos_hint: {"x": 0, "y": 0}
        source: 'images/heartside.gif'
        allow_stretch: True
        keep_ratio: False
        anim_delay: 0.07



    Image:
        size_hint: (.274, .7)
        pos_hint: {"x": .666, "y": .08}
        source: 'images/betterobama.png'
        allow_stretch: False
        keep_ratio: False

    Image:
        size_hint: (.274, .7)
        pos_hint: {"x": .366, "y": .08}
        source: 'images/smiling_earth_cropped.png'
        allow_stretch: False
        keep_ratio: False

    Image:
        size_hint: (.274, .7)
        pos_hint: {"x": .067, "y": .08}
        source: 'images/nyabyssalbetter.png'
        allow_stretch: False
        keep_ratio: False

    Button:
        size_hint: (.277, .205)
        pos_hint: {"x":.0655, "y":.0475}
        background_normal: ''
        background_color: 200/255, 0, 70/255

    Button:
        size_hint: (.274, .2)
        pos_hint: {"x":.067, "y":.049}
        background_normal: ''
        background_color: 1, .5, .6, .85
        font_size: 45
        bold: True
        color: 200/255, 0/255, 70/255, 1
        text: "Nyabyssal"
        on_release: root.manager.current = "second"
        on_release: root.manager.transition = FadeTransition()
        font_name: 'Micross'

    Button:
        size_hint: (.278, .205)
        pos_hint: {"x":.3645, "y":.0475}
        background_normal: ''
        background_color: 200/255, 0, 70/255

    Button:
        size_hint: (.274, .2)
        pos_hint: {"x":.366, "y":.049}
        background_normal: ''
        background_color: 1, .5, .6, .85
        font_size: 40
        bold: True
        color: 200/255, 0/255, 70/255, 1
        text: "Earth-chan"
        font_name: 'Micross'

    Button:
        size_hint: (.278, .205)
        pos_hint: {"x":.6645, "y":.0475}
        background_normal: ''
        background_color: 200/255, 0, 70/255

    Button:
        size_hint: (.274, .2)
        pos_hint: {"x":.666, "y":.049}
        background_normal: ''
        background_color: 1, .5, .6, .85
        font_size: 50
        bold: True
        color: 200/255, 0/255, 70/255, 1
        text: "Obama"
        font_name: 'Micross'

    Button:
        size_hint: (.4, .2)
        pos_hint: {"x":-0.001, "y":0.8}
        background_normal: ''
        background_color: 255/255, 6/255, 0/255, 1
        font_size: 60
        bold: True
        color: 200/255, 0/255, 70/255, 1
        disabled: True

    Button:
        size_hint: (.8, .2)
        pos_hint: {"x":.394, "y":0.8}
        background_normal: ''
        background_color: 1, .3, .4, 1
        font_size: 50
        bold: True
        color: 200/255, 0/255, 70/255, 1
        disabled: True

    Image:
        source: 'images/dating_sim_grad.png'
        size_hint: (.5, .15)
        pos_hint: {"x": 0.4, "y": 0.82}
        allow_stretch: True
        keep_ratio: False

    Image:
        source: 'images/CandL.png'
        size_hint: (0.4, 0.2)
        pos_hint: {"x": -0.001, "y": 0.8}
        allow_stretch: True
        keep_ratio: False
    Button:
        size_hint: (.074, .08)
        pos_hint: {"x":.9285, "y":.847}
        background_normal: ''
        background_color: 200/255, 0, 70/255
    Button:
        size_hint: (.11, .075)
        pos_hint: {"x":.89, "y":.925}
        background_normal: ''
        background_color: 1, .5, .6, .85
        font_size: 22
        bold: True
        text: "Settings"
        color: 200/255, 0/250, 70/255, 1
        on_release: Factory.Setting().open()
    Button:
        size_hint: (.07, .075)
        pos_hint: {"x":.93, "y":.8485}
        background_normal: ''
        background_color: 1, .5, .6, .85
        font_size: 50
        bold: True
        text: "?"
        color: 200/255, 0/250, 70/255, 1
        on_release: Factory.Question().open()


<SecondScreen>:
    FloatLayout:
        Button:
            id: buttonfortext
            text: "Go to third"
            pos_hint: {"x": 0, "y": 0}
            size_hint: 1, .2
            on_release: root.manager.transition = NoTransition()
            on_release: root.manager.current = "third"

            disabled: True

        Button: #right
            id: idforb
            text: "text here"
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .1
            on_release: root.manager.current = "third"
            on_release: root.manager.transition = FadeTransition()
            #on_release: app.text_wait("text test", "idforuser", "second")

        Button: #left
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .1
            on_release: root.manager.current = "a77"

        Image:
            source: 'images/genshinbg1.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\n Hiya, I'm Nyabyssal! I'm a nice, charismatic girl who loves playing games. \n It's nice to meet you, Anon! ^.^"
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'

        Label:
            id: idforuser
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .1
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Nice to meet you too!"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .1
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Aren't you Hu Tao from Genshi-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'

<winner>:
    Button:
        text: "winner"

<loer>:
    Button:
        text: "loer"

<ThirdScreen>:
    Button:
        pos_hint: {"x": 0, "y": 0}
        size_hint: 1, .2
        on_release: root.manager.current = "fifth"
        on_release: root.manager.transition = FadeTransition()

    Image:
        source: 'images/angrygenshinbg.jpg'
        size_hint: 1,0.8
        pos_hint: {"x": 0, "y": 0.2}
        allow_stretch: True
        keep_ratio: False
    Image:
        source: 'images/textbox.png'
        pos_hint: {"x": -.1, "y": -.1}
        size_hint: 1.25, .55
        allow_stretch: True
        keep_ratio: False
        Label:
            text: "\n\n\n SHUT UP I AM NYABYSSAL, THE GOD OF ROGUE LINEAGE!! I DO NOT WANT TO \n BE ASSOCIATED WITH GENSHIN TRASH!!! OH MY GOD I will literally send you to \n purgatory (I am rank 1 deep knight)"
            font_size: 20
            center: self.parent.center
            color: 1, 0, .3, 1
            font_name: 'Micross'
    Label:
        text: "Nyabyssal"
        bold: True
        font_size: 20
        pos_hint: {"x": -0.4, "y": -0.29}
        color: 200/255, 0/255, 70/255, 1
        font_name: 'Micross'
    Image:
        source: 'images/hutao.png'
        pos_hint: {"x": 0.25, "y": 0.25}
        size_hint: .7, .7
        allow_stretch: False
        keep_ratio: False
    Image:
        source: 'images/angery.png'
        size_hint: 0.05, 0.05
        pos_hint: {"x": 0.595, "y": 0.845}
        allow_stretch: False
        keep_ratio: False


<FourthScreen>:
    Button:

        text: "Go to third"
        pos_hint: {"x": 0, "y": 0}
        size_hint: 1, .2
        on_release: root.manager.current = "fifth"
    Image:
        source: 'images/genshinbg1.jpg'
        size_hint: 1,0.8
        pos_hint: {"x": 0, "y": 0.2}
        allow_stretch: True
        keep_ratio: False
    Image:
        source: 'images/textbox.png'
        pos_hint: {"x": -.1, "y": -.1}
        size_hint: 1.25, .55
        allow_stretch: True
        keep_ratio: False
    Label:
        text: "Nyabyssal"
        bold: True
        font_size: 20
        pos_hint: {"x": -0.4, "y": -0.29}
        color: 200/255, 0/255, 70/255, 1
        font_name: 'Micross'
    Image:
        source: 'images/textbox.png'
        pos_hint: {"x": -.1, "y": -.1}
        size_hint: 1.25, .55
        allow_stretch: True
        keep_ratio: False
        Label:
            text: "wait you weren't supposed to pick this (i am not done making it)"
            font_size: 20
            center: self.parent.center
            color: 1, 0, .3, 1
            font_name: 'Micross'

    Image:
        source: 'images/hutao.png'
        pos_hint: {"x": 0.25, "y": 0.25}
        size_hint: .7, .7
        allow_stretch: False
        keep_ratio: False
<Five>:

    Button:
        text: "Go to third"
        pos_hint: {"x": 0, "y": 0}
        size_hint: 1, .2
        on_release: root.manager.current = "sixth"
        disabled: True
    Button: #right
        pos_hint: {"x": 0.59, "y": 0.01}
        size_hint: .35, .1
        on_release: root.manager.current = "seventh"
        on_release: root.manager.transition = PixelTransition(duration = 1.5 )
    Button: #left
        pos_hint: {"x": 0.09, "y": 0.01}
        size_hint: .35, .1
        on_release: root.manager.current = "sixth"

    Image:
        source: 'images/genshinbg1.jpg'
        size_hint: 1,0.8
        pos_hint: {"x": 0, "y": 0.2}
        allow_stretch: True
        keep_ratio: False
    Image:
        source: 'images/textbox.png'
        pos_hint: {"x": -.1, "y": -.1}
        size_hint: 1.25, .55
        allow_stretch: True
        keep_ratio: False
        Label:
            text: "\n\nGonna be honest here, this relationship isn't going to work out. Though if you want, I \ncan introduce you to Enimul. She'a also a Genshin fan like you.."
            font_size: 20
            center: self.parent.center
            color: 1, 0, .3, 1
            font_name: 'Micross'
    Label:
        text: "Nyabyssal"
        bold: True
        font_size: 20
        pos_hint: {"x": -0.4, "y": -0.29}
        color: 200/255, 0/255, 70/255, 1
        font_name: 'Micross'
    Image:
        source: 'images/hutao.png'
        pos_hint: {"x": 0.25, "y": 0.25}
        size_hint: .7, .7
        allow_stretch: False
        keep_ratio: False

    Image:
        source: 'images/responsebox.png'
        pos_hint: {"x": 0.09, "y": 0.01}
        size_hint: .35, .08
        allow_stretch: True
        keep_ratio: False
        Label:
            text: "Uhh, okay then. Let me \ntalk to her instead."
            font_size: 15
            center: self.parent.center
            color: 0, 0, 0, 1
            font_name: 'Micross'
    Image:
        source: 'images/responsebox.png'
        pos_hint: {"x": 0.59, "y": 0.01}
        size_hint: .35, .08
        allow_stretch: True
        keep_ratio: False
        Label:
            text: "No, I hate women."
            font_size: 15
            center: self.parent.center
            color: 0, 0, 0, 1
            font_name: 'Micross'
<Six>:

    Button: #middle
        pos_hint: {"x": 0.34, "y": 0.01}
        size_hint: .35, .1
        on_release: root.manager.current = "eighth"
    Image:
        source: 'images/genshinbg1.jpg'
        size_hint: 1,0.8
        pos_hint: {"x": 0, "y": 0.2}
        allow_stretch: True
        keep_ratio: False
    Image:
        source: 'images/textbox.png'
        pos_hint: {"x": -.1, "y": -.1}
        size_hint: 1.25, .55
        allow_stretch: True
        keep_ratio: False
        Label:
            text: "\n\nYou're missing out on your one and only chance to become friends with the cool \n and epic Nyabyssal but sure I guess lets gooooooooo *snaps fingers epically*"
            font_size: 20
            center: self.parent.center
            color: 1, 0, .3, 1
            font_name: 'Micross'
    Label:
        text: "Nyabyssal"
        bold: True
        font_size: 20
        pos_hint: {"x": -0.4, "y": -0.29}
        color: 200/255, 0/255, 70/255, 1
        font_name: 'Micross'

    Image:
        source: 'images/hutao.png'
        pos_hint: {"x": 0.25, "y": 0.25}
        size_hint: .7, .7
        allow_stretch: False
        keep_ratio: False
    Image:
        source: 'images/responsebox.png'
        pos_hint: {"x": 0.34, "y": 0.01}
        size_hint: .35, .08
        allow_stretch: True
        keep_ratio: False
        Label:
            text: "You're so cringe, this isn't an anime."
            font_size: 15
            center: self.parent.center
            color: 0, 0, 0, 1
            font_name: 'Micross'

<Seven>:
    FloatLayout:
        Button:

            text: "Go to third"
            pos_hint: {"x": 0, "y": 0}
            size_hint: 1, .2
            on_release: root.manager.current = "crash"
            on_release: app.Crash()
        Image:
            source: 'images/angery.png'
            size_hint: 0.05, 0.05
            pos_hint: {"x": 0.595, "y": 0.845}
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/angrygenshinbg.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\n\nWhy are you even playing a dating\nsim then GET OUT!!"
                font_size: 45
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1
            font_name: 'Micross'
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/angery.png'
            size_hint: 0.05, 0.05
            pos_hint: {"x": 0.595, "y": 0.845}
            allow_stretch: False
            keep_ratio: False

<Eight>:

    Button: #middle
        id: middlebuttoneight
        pos_hint: {"x": 0.34, "y": 0.01}
        size_hint: .35, .1
        #on_release: root.manager.current = "ninth"
        on_release: root.manager.transition = BlurTransition(duration = 1 )

        on_release: root.gowhite()
        on_release: root.manager.transition = BlurTransition(duration = 1 )

    Image:
        source: 'images/genshinbg1.jpg'
        size_hint: 1,0.8
        pos_hint: {"x": 0, "y": 0.2}
        allow_stretch: True
        keep_ratio: False
    Image:
        pos_hint: {"x": .225, "y": -.31}
        source: 'images/actualgaterogue.png'
        allow_stretch: False
        keep_ratio: False
    Image:
        source: 'images/textbox.png'
        pos_hint: {"x": -.1, "y": -.1}
        size_hint: 1.25, .55
        allow_stretch: True
        keep_ratio: False
        Label:
            text: "\n\nYou're missing out on your one and only chance to become friends with the cool \n and epic Nyabyssal but sure I guess lets gooooooooo *snaps fingers epically*"
            font_size: 20
            center: self.parent.center
            color: 1, 0, .3, 1
            font_name: 'Micross'
    Label:
        text: "Nyabyssal"
        bold: True
        font_size: 20
        pos_hint: {"x": -0.4, "y": -0.29}
        color: 200/255, 0/255, 70/255, 1
        font_name: 'Micross'

    Image:
        source: 'images/hutao.png'
        pos_hint: {"x": 0.25, "y": 0.25}
        size_hint: .7, .7
        allow_stretch: False
        keep_ratio: False
    Image:
        source: 'images/responsebox.png'
        pos_hint: {"x": 0.34, "y": 0.01}
        size_hint: .35, .08
        allow_stretch: True
        keep_ratio: False
        Label:
            text: "WHAT HOW DID THAT JUST APPEAR??"
            font_size: 14
            center: self.parent.center
            color: 0, 0, 0, 1
            font_name: 'Micross'

<Nine>:
    FloatLayout:
        Button: #middle
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .1
            on_release: root.manager.transition = FadeTransition()
            on_release: root.manager.current = "tenth"
            on_release: root.manager.transition = FadeTransition()
        Image:
            source: 'images/genshinluminabg.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.238}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\n\nWe're here! This is the Nantianmen. Eminul likes frequenting here, it's a place where \nshe can relax in peace. She's over there, let's walk over."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1
            font_name: 'Micross'
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Okay, let's go."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'


<Ten>:
    FloatLayout:
        Button:

            text: "Go to third"
            pos_hint: {"x": 0, "y": 0}
            size_hint: 1, .2
            on_release: root.manager.current = "eleventh"
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nEnimul, this is Anon. Anon, this is Enimul. Say hi to each other."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1
            font_name: 'Micross'
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

<Eleven>:
    FloatLayout:
        Button: #rihgt
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .1
            on_release: root.giveelevenaffinity()
            on_release: root.manager.current = "twelfth"

        Button: #left
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .1
            on_release: root.manager.current = "thirteenth"

        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\n\nO-oh, hey Nyabyssal. Is this the person you were talking about? Hi Anon, I'm Enimul. \nIt's nice to meet you, I hope we can be good friends."
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Hi, it's nice to meet you too. I'm Anon."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Omg are you cosplaying a Genshin \ncharacter? Are you also a Genshin fan?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'

<Twelve>:
    FloatLayout:
        Button:
            pos_hint: {"x": 0, "y": 0}
            size_hint: 1, .2
            on_release: root.manager.current = "thirteenth"
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False


        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\n\n\n Y-yeah, she's one of my favorite characters. I'm a pretty big Genshin fan. \n I also happen to spend a lot of money on it, but I just love Genshin that much.."
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            size_hint: .045, .05
            pos_hint: {"x": .3375, "y": .83}
            source: 'images/blush.png'
            allow_stretch: False
            keep_ratio: False


<Thirteen>:
    FloatLayout:
        Button: #rihgt
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .1
            #on_release: root.manager.current = "fourteenth"
            on_release: root.funny()

        Button: #left
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .1
            #on_release: root.manager.current = "fourteenth"
            on_release: root.funny()


        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            id: whitecircle1
            source: 'images/whitecircle.png'
            pos_hint: {"x": 0.1, "y": -1.5}
            allow_stretch: True
            keep_ratio: True
            opacity: 0


        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'

<Fourteen>:
    FloatLayout:
        Button: #right
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .1
            on_release: root.manager.current = "a57"
        Button: #left
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .1
            on_release: root.manager.current = "a54"
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nUmm, where would you like to go now, Anon?"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Let's go to a cafe maybe? "
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Uhhhhhhhhhhhhhhhhh your house? ;)"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'

<Fifteen>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .1, .1
            pos_hint: {"x": 0.55, "y": 0.675}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<Sixteen>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
            opacity: 0
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            pos_hint: {"x": 0.25, "y": 0.3}
            allow_stretch: True
            keep_ratio: True
            opacity: 0
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a17>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .15, .15
            pos_hint: {"x": 0.525, "y": 0.65}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a18>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .2, .2
            pos_hint: {"x": 0.5, "y": 0.625}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a19>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .25, .25
            pos_hint: {"x": 0.475, "y": 0.6}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a20>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .3, .3
            pos_hint: {"x": 0.45, "y": 0.575}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a21>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .35, .35
            pos_hint: {"x": 0.425, "y": 0.55}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a22>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .4, .4
            pos_hint: {"x": 0.4, "y": 0.525}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a23>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .45, .45
            pos_hint: {"x": 0.375, "y": 0.5}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a24>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .5, .5
            pos_hint: {"x": 0.35, "y": 0.475}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a25>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .55, .55
            pos_hint: {"x": 0.325, "y": 0.45}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a26>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .6, .6
            pos_hint: {"x": 0.3, "y": 0.425}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'

<a27>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .65, .65
            pos_hint: {"x": 0.275, "y": 0.4}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a28>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .7, .7
            pos_hint: {"x": 0.25, "y": 0.375}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'

<a29>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .75, .75
            pos_hint: {"x": 0.225, "y": 0.35}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a30>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .8, .8
            pos_hint: {"x": 0.2, "y": 0.325}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a31>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .85, .85
            pos_hint: {"x": 0.175, "y": 0.3}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a32>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .9, .9
            pos_hint: {"x": 0.15, "y": 0.275}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a33>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .95, .95
            pos_hint: {"x": 0.125, "y": 0.25}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a34>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            pos_hint: {"x": .225, "y": -.31}
            source: 'images/actualgaterogue.png'
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/hutao.png'
            pos_hint: {"x": 0.25, "y": 0.25}
            size_hint: .7, .7
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: 1, 1
            pos_hint: {"x": 0.1, "y": 0.225}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a35>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .95, .95
            pos_hint: {"x": 0.125, "y": 0.25}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a36>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .9, .9
            pos_hint: {"x": 0.15, "y": 0.275}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a37>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .85, .85
            pos_hint: {"x": 0.175, "y": 0.3}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a38>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .8, .8
            pos_hint: {"x": 0.2, "y": 0.325}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a39>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .75, .75
            pos_hint: {"x": 0.225, "y": 0.35}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a40>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a41>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .65, .65
            pos_hint: {"x": 0.275, "y": 0.4}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a42>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .6, .6
            pos_hint: {"x": 0.3, "y": 0.425}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a43>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .55, .55
            pos_hint: {"x": 0.325, "y": 0.45}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a44>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .5, .5
            pos_hint: {"x": 0.35, "y": 0.475}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a45>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .45, .45
            pos_hint: {"x": 0.375, "y": 0.5}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a46>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .4, .4
            pos_hint: {"x": 0.4, "y": 0.525}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a47>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .35, .35
            pos_hint: {"x": 0.425, "y": 0.55}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a48>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .3, .3
            pos_hint: {"x": 0.45, "y": 0.575}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a49>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/whitecircle.png'
            size_hint: .25, .25
            pos_hint: {"x": 0.475, "y": 0.6}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a50>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .2, .2
            pos_hint: {"x": 0.5, "y": 0.625}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a51>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .15, .15
            pos_hint: {"x": 0.525, "y": 0.65}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a52>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .1, .1
            pos_hint: {"x": 0.55, "y": 0.675}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a53>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .05, .05
            pos_hint: {"x": 0.575, "y": 0.7}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a56>:
    FloatLayout:
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False

        Image:
            source: 'images/whitecircle.png'
            size_hint: .025, .025
            pos_hint: {"x": 0.5875  , "y": 0.7125}
            allow_stretch: True
            keep_ratio: True

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nWell, you guys seem to be getting along. I'm gonna go now, have \nfun with your vi- I mean uhh friend."
                font_size: 20
                center: self.parent.center
                color: 1, 0, .3, 1
                font_name: 'Micross'
        Label:
            text: "Nyabyssal"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 200/255, 0/255, 70/255, 1,
            font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "See ya later shtinky."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Wait, what?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'

<a55>:
    FloatLayout:
        Button:
            pos_hint: {"x": 0, "y": 0}
            size_hint: 1, .2
            on_release: root.funy2()
            on_release: root.manager.transition = BlurTransition(duration = 1 )

        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nO-oh, um, okay. Let me take us there."
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'


<a54>:
    FloatLayout:

        Button:
            pos_hint: {"x":0, "y":0}
            size_hint: 1, .2
            on_release: root.manager.transition = BlurTransition(duration = 1 )
            on_release: root.gowhite()
            on_release: root.manager.transition = BlurTransition(duration = 1 )

        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nSure, I have one in mind. Let me take us there."
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'
<a57>:
    FloatLayout:
        Button: #right
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .1
            on_release: root.manager.transition = BlurTransition(duration = 1 )
            on_release: root.afficheckyes()

        Button: #left
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .1
            on_release: root.manager.current = "a54"
        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nA-are you sure? My house is very messy, and umm..."
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Nevermind, let's go to a cafe."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Yes, I'm sure."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a58>:

<a59>:
    FloatLayout:
        Button: #right
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .1
            on_release: root.check()
            on_release: root.manager.current = "a55"
            on_release: root.manager.transition = FadeTransition()

        Button: #left
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .1
            on_release: root.manager.transition = FadeTransition()
            on_release: root.manager.current = "a54"
            on_release: root.manager.transition = FadeTransition()

        Image:
            source: 'images/genshinbg2.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nR-really? I-I'm kind of scared about having you over here... are you certain?"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/lumine.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.09, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Oh, alright then. Let's go to a cafe."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.59, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Yes, I'm 100% sure."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a60>:
    FloatLayout:

        Button: #middle
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .1
            on_release: root.manager.transition = FadeTransition()
            on_release: root.manager.current = "a61"
            on_release: root.manager.transition = FadeTransition()

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nOkay, we’re here! S-sorry, let me open the curtains."
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Yeah, it's very dark. \nPlease open the curtains."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a61>:
    FloatLayout:
        Button: #middle
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .1
            on_release: root.manager.transition = RVBTransition(duration=0.05)
            on_release: root.manager.current = "a62"
            on_release: root.manager.transition = RVBTransition(duration=0.05)
            #on_release: app.play_sound()


        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": 0, "y": 0.25}
            size_hint: .71, .71
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nI-I'm sorry, Anon, but I need more money... and I've been ordered to kill you.."
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "W-wait, what? Hold up a minu-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a62>:
    FloatLayout:
        Button: #middle
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .1
            on_release: root.manager.current = "a62"
        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": -0.23, "y": 0.13}
            size_hint: 1.023, 1.023
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'

<a63>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": -0.46, "y": 0.01}
            size_hint: 1.336, 1.336
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'

<a64>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": -0.69, "y": -0.11}
            size_hint: 1.649, 1.649
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a65>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": -0.92, "y": -0.23}
            size_hint: 1.962, 1.962
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a66>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": -1.15, "y": -0.35}
            size_hint: 2.275, 2.275
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a67>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": -1.28, "y": -0.47}
            size_hint: 2.588, 2.588
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a68>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": -1.51, "y": -0.59}
            size_hint: 2.901, 2.901
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a69>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": -1.74, "y": -0.71}
            size_hint: 3.214, 3.214
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a70>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": -1.97, "y": -0.83}
            size_hint: 3.527, 3.527
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a71>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": -2.2, "y": -0.95}
            size_hint: 3.84, 3.84
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a72>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": -2.43, "y": -1.07}
            size_hint: 4.153, 4.153
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a73>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroom.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecrop.png'
            pos_hint: {"x": -2.66, "y": -1.19}
            size_hint: 4.466, 4.466
            allow_stretch: False
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a74>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroomdedge.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecropdedge.png'
            pos_hint: {"x": -2.8, "y": -1.23}
            size_hint: 4.2, 4.2
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a75>:
    FloatLayout:

        Image:
            source: 'images/genshinimpactroomdedge.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/actualscaryluminecropdedge.png'
            pos_hint: {"x": -3.7, "y": -2.13}
            size_hint: 6, 6
            allow_stretch: True
            keep_ratio: False
        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nGoodbye Anon!!!! I'm sorry about this!!!"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
<a76>:
    FloatLayout:


        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.34, "y": 0.01}
            size_hint: .35, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "We can talk about this WAIT PLEA-"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'

<a77>:
    FloatLayout:
        Button: #left, +10
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            on_release: root.plus10affinity()
            on_release: root.manager.transition = FadeTransition()
            on_release: root.manager.current = "a78"
            on_release: root.manager.transition = FadeTransition()
        Button: #middlemaybe +3
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            on_release: root.plus3affinity()
            on_release: root.manager.transition = FadeTransition()
            on_release: root.manager.current = "a79"
            on_release: root.manager.transition = FadeTransition()
        Button: #right, -5
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            on_release: root.minus5affinity()
            on_release: root.manager.transition = FadeTransition()
            on_release: root.manager.current = "a80"
            on_release: root.manager.transition = FadeTransition()

        Image:
            source: 'images/cafemaybe2.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nW-we're here! This is my favorite cafe in this area. D-do you want some drinks?"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Sure, can I get a Tart Brilliance?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Sure, can I get an Athenaeum?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Uhh, I don't like drinking. "
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

<a78>:
    FloatLayout:

        Button: #left
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            on_release: root.minus3affinity()
            on_release: root.manager.current = "a83"
        Button: #middlemaybe
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            on_release: root.plus10affinity()
            on_release: root.manager.current = "a83"
        Button: #right
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            on_release: root.minus15affinity()
            on_release: root.manager.current = "a83"

        Image:
            source: 'images/betterluminecafeturned.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\n\nO-oh, that's a good choice. I also really like that. U-um, waiter, can we get a \nTart Brilliance and a Brightcrown?"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Thanks for ordering for me. I don't really \nlike talking to random people, even waiters."
                font_size: 11.2
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Thanks for ordering for me. I'm \nreally shy about things like this."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Thanks for ordering for me. I'm \nbroke and have no money."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'
<a79>:
    FloatLayout:
        Button: #left
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            on_release: root.minus3affinity()
            on_release: root.manager.current = "a82"
        Button: #middlemaybe
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            on_release: root.plus10affinity()
            on_release: root.manager.current = "a82"
        Button: #right
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            on_release: root.minus15affinity()
            on_release: root.manager.current = "a82"

        Image:
            source: 'images/betterluminecafeturned.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nO-oh, okay. U-um, waiter, can we get an Athenaeum and a Brightcrown?"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Thanks for ordering for me. I don't really \nlike talking to random people, even waiters."
                font_size: 11.2
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Thanks for ordering for me. I'm \nreally shy about things like this."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Thanks for ordering for me. I'm \nbroke and have no money."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'
<a80>:
    FloatLayout:

        Button: #left
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            on_release: root.manager.current = "a81"
        Button: #middlemaybe
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            on_release: root.minus10affinity()
            on_release: root.manager.current = "a81"
        Button: #right
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            on_release: root.plus15affinity()
            on_release: root.manager.current = "a81"

        Image:
            source: 'images/betterluminecafeturned.jpg'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\n\nO-oh. Umm, okay. Uhm... I'll just take a Brightcrown for myself then. U-um, waiter, \ncan I get a Brightcrown?"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Thanks."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Thanks, I really don't like drinking. \nI'm allergic to water."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Oh, sorry about that. I probably should've \n ordered something to make it not awkward..."
                font_size: 11
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

<a81>: #no thing
    FloatLayout:
        Button: #left
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            on_release: root.plus6affinity()
            on_release: root.manager.current = "a86"
        Button: #middlemaybe
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            on_release: root.afficheck()
        Button: #right
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            on_release: root.plus6affinity()
            on_release: root.manager.current = "a86"

        Image:
            source: 'images/nothingcafe.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nO-oh, no worries. Um... I don't really know what to do now. What do you want to \ntalk about?"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "What do you like to do?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Let's go back to your house. "
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "I want to know more about you."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'
<a82>: #coffe
    FloatLayout:
        Button: #left
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            on_release: root.plus6affinity()
            on_release: root.manager.current = "a89"
        Button: #middlemaybe
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            on_release: root.afficheck()
        Button: #right
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            on_release: root.plus6affinity()
            on_release: root.manager.current = "a89"

        Image:
            source: 'images/athenaeum.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nO-oh, no worries. Here's your Athenaeum. Um... I don't really know what to do now.\nWhat do you want to talk about?"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "What do you like to do?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Let's go back to your house. "
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "I want to know more about you."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'
<a83>: #good one (tart)
    FloatLayout:
        Button: #left
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            on_release: root.plus6affinity()
            on_release: root.manager.current = "a90"
        Button: #middlemaybe
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            on_release: root.afficheck()
        Button: #right
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            on_release: root.plus6affinity()
            on_release: root.manager.current = "a90"

        Image:
            source: 'images/tartbrilliance.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nO-oh, no worries. Here's your Tart Brilliance. Um... I don't really know what to do now.\nWhat do you want to talk about?"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.033, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "What do you like to do?"
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.35, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "Let's go back to your house. "
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Image:
            source: 'images/responsebox.png'
            pos_hint: {"x": 0.667, "y": 0.01}
            size_hint: .3, .08
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "I want to know more about you."
                font_size: 15
                center: self.parent.center
                color: 0, 0, 0, 1
                font_name: 'Micross'
        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'
<a84>: #nothing, affinity > 75
    FloatLayout:

        Button:
            text: "Go to third"
            pos_hint: {"x": 0, "y": 0}
            size_hint: 1, .2
            on_release: root.manager.current = "a86"

        Image:
            source: 'images/nothingcafe.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nU-um, I don't know about that... Oh, I know! How about we talk about our interests?"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'

        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

<a85>: #nothing, affinity < 75
    FloatLayout:

        Button:
            text: "Go to third"
            pos_hint: {"x": 0, "y": 0}
            size_hint: 1, .2
            on_release: root.manager.transition = BlurTransition(duration = 1 )
            on_release: root.gowhite()
            on_release: root.manager.transition = BlurTransition(duration = 1 )

        Image:
            source: 'images/nothingcafe.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nOh. What a shame... I wanted to stay here a bit longer. Let's teleport there then. "
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'

        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

<a87>: #coffee, affinity > 75
    FloatLayout:

        Button:
            text: "Go to third"
            pos_hint: {"x": 0, "y": 0}
            size_hint: 1, .2
            on_release: root.manager.current = "a89"

        Image:
            source: 'images/athenaeum.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nU-um, I don't know about that... Oh, I know! How about we talk about our interests?"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'

        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

<a88>: #coffe, affinity < 75

    FloatLayout:

        Button:
            text: "Go to third"
            pos_hint: {"x": 0, "y": 0}
            size_hint: 1, .2
            on_release: root.manager.transition = BlurTransition(duration = 1 )
            on_release: root.gowhite()
            on_release: root.manager.transition = BlurTransition(duration = 1 )

        Image:
            source: 'images/athenaeum.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nOh. What a shame... I wanted to stay here a bit longer. Let's teleport there then. "
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'

        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'
<a91>: #tart, affi > 75
    FloatLayout:

        Button:
            text: "Go to third"
            pos_hint: {"x": 0, "y": 0}
            size_hint: 1, .2
            on_release: root.manager.current = "a90"

        Image:
            source: 'images/tartbrilliance.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nU-um, I don't know about that... Oh, I know! How about we talk about our interests?"
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'

        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'

<a92>: #tart, affi < 75

    FloatLayout:

        Button:
            text: "Go to third"
            pos_hint: {"x": 0, "y": 0}
            size_hint: 1, .2
            on_release: root.manager.transition = BlurTransition(duration = 1 )
            on_release: root.gowhite()
            on_release: root.manager.transition = BlurTransition(duration = 1 )

        Image:
            source: 'images/tartbrilliance.png'
            size_hint: 1,0.8
            pos_hint: {"x": 0, "y": 0.2}
            allow_stretch: True
            keep_ratio: False

        Image:
            source: 'images/textbox.png'
            pos_hint: {"x": -.1, "y": -.1}
            size_hint: 1.25, .55
            allow_stretch: True
            keep_ratio: False
            Label:
                text: "\nOh. What a shame... I wanted to stay here a bit longer. Let's teleport there then. "
                font_size: 20
                center: self.parent.center
                color: 255/255, 230/255, 140/205, 1
                font_name: 'Micross'

        Label:
            text: "Enimul"
            bold: True
            font_size: 20
            pos_hint: {"x": -0.4, "y": -0.29}
            color: 189/255, 183/255, 107/255, 1
            font_name: 'Micross'
<a89>: #coffe, more about her. Interests
<a86>: #nothing, more about her. Interests
<a90>: #tart, more about her. interests


<blackscreen>:

<whitescreen>:
    Image:
        source: 'images/whitecircle.png'
        size_hint: 2, 2
        pos_hint: {"x": -.5, "y": -0.5}
        allow_stretch: True
        keep_ratio: True

