#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import Gradient kivy_gradient.Gradient

<FirstScreen>:
    canvas:
        #Color:
        #    rgb: (255/255, 170/255, 235/255)
        Rectangle:
            pos: self.pos
            size: self.size
            texture:
                Gradient.vertical(
                get_color_from_hex("E91E63"),
                get_color_from_hex("FCE4EC"),
                get_color_from_hex("2962FF")
                )

    Image:
        size_hint: (1, 1)
        pos_hint: {"x": 0, "y": 0}
        source: 'images/floating_heart_zip.zip'
        #source: 'images/heart_float.gif'
        allow_stretch: True
        keep_ratio: False

    Image:
        size_hint: (.274, .7)
        pos_hint: {"x": .666, "y": .08}
        source: 'images/Obama.jpg'
        allow_stretch: False
        keep_ratio: False

    Image:
        size_hint: (.274, .7)
        pos_hint: {"x": .366, "y": .08}
        source: 'images/smiling_earth_cropped.png'
        allow_stretch: False
        keep_ratio: False

    Image:
        size_hint: (.274, .7)
        pos_hint: {"x": .067, "y": .08}
        source: 'images/nyabyssalbetter.png'
        allow_stretch: False
        keep_ratio: False

    Button:
        size_hint: (.277, .205)
        pos_hint: {"x":.0655, "y":.0475}
        background_normal: ''
        background_color: 200/255, 0, 70/255

    Button:
        id: obama_text
        size_hint: (.274, .2)
        pos_hint: {"x":.067, "y":.049}
        background_normal: ''
        background_color: 1, .5, .6, .85
        font_size: 45
        bold: True
        color: 200/255, 0/255, 70/255, 1
        text: "Nyabyssal"
        on_release: root.manager.current = "second"
        font_name: 'Micross'

    Button:
        size_hint: (.278, .205)
        pos_hint: {"x":.3645, "y":.0475}
        background_normal: ''
        background_color: 200/255, 0, 70/255

    Button:
        size_hint: (.274, .2)
        pos_hint: {"x":.366, "y":.049}
        background_normal: ''
        background_color: 1, .5, .6, .85
        font_size: 40
        bold: True
        color: 200/255, 0/255, 70/255, 1
        text: "Earth-chan"
        font_name: 'Micross'

    Button:
        size_hint: (.278, .205)
        pos_hint: {"x":.6645, "y":.0475}
        background_normal: ''
        background_color: 200/255, 0, 70/255

    Button:
        size_hint: (.274, .2)
        pos_hint: {"x":.666, "y":.049}
        background_normal: ''
        background_color: 1, .5, .6, .85
        font_size: 50
        bold: True
        color: 200/255, 0/255, 70/255, 1
        text: "Obama"
        font_name: 'Micross'

    Button:
        size_hint: (.285, .2)
        pos_hint: {"x":-0.001, "y":0.8}
        background_normal: ''
        background_color: 255/255, 6/255, 0/255, 1
        font_size: 60
        bold: True
        color: 200/255, 0/255, 70/255, 1
        disabled: True

    Button:
        size_hint: (.8, .2)
        pos_hint: {"x":.28, "y":0.8}
        background_normal: ''
        background_color: 1, .3, .4, 1
        font_size: 50
        bold: True
        color: 200/255, 0/255, 70/255, 1
        disabled: True

    Image:
        source: 'images/dating_sim_grad.png'
        size_hint: (1, 1)
        pos_hint: {"x": 0.1, "y": 0.4}
        allow_stretch: False
        keep_ratio: False

    Image:
        source: 'images/CandL.png'
        size_hint: (0.98, 0.98)
        pos_hint: {"x": -0.35, "y": 0.42}
        allow_stretch: False
        keep_ratio: False


<SecondScreen>:
    FloatLayout:
        Button:
            id: buttonfortext
            text: "Go to third"
            pos_hint: {"center_x": .5, "center_y": .5}
            size_hint: .2, .2
            on_release: root.manager.current = "third"
            on_release: app.text_wait("burger")

<ThirdScreen>:
    FloatLayout:
        Button:
            text: "WHAT"
            size_hint: .3, .1
            pos_hint: {"x": .3, "y": .5}
            on_release: root.manager.current = "fourth"

<FourthScreen>:
    FloatLayout:
        Button:
            text: "magic!"
            size_hint: .3, .1
            pos_hint: {"x": .3, "y": .5}
            on_release: root.manager.current = "first"

